"""Script to generate eda/02_model_experiments_daily_forecasting.ipynb with WAPE metric integrated."""

import json
from pathlib import Path

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# ⚡ EPİAŞ PTF Forecast - Dedicated Model Experiments Notebook\n",
                "\n",
                "**Proje:** Türkiye Elektrik Piyasası Piyasa Takas Fiyatı (PTF - USD/MWh & TL/MWh) Tahmini  \n",
                "**Görev (Task):** Günlük Gün Öncesi Piyasası (GÖP) için yarının **24 saatlik fiyat bloğunun** tahmin edilmesi.  \n",
                "**Metrikler:** **MAE ($/MWh)**, **MAPE (%)** ve **WAPE (% - Weighted Absolute Percentage Error)**  \n",
                "**Doğrulama Stratejisi (Backtest):** Her gün geriye giderek modeli son 6 ayın verisiyle eğitip yarının 24 saatini tahmin eden **Günlük Walk-Forward Backtest**.  \n",
                "**Raporlama Ufku:** Geriye dönük **Son 3 Ay (90 Gün)**, **Son 6 Ay (180 Gün)**, **Son 9 Ay (270 Gün)** ve **Son 12 Ay (365 Gün)** Metrik Ortalamaları.  \n",
                "\n",
                "---"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 1. Kütüphanelerin Yüklenmesi ve Veritabanı Bağlantısı"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import os\n",
                "import sys\n",
                "from pathlib import Path\n",
                "import numpy as np\n",
                "import pandas as pd\n",
                "import matplotlib.pyplot as plt\n",
                "import seaborn as sns\n",
                "import warnings\n",
                "warnings.filterwarnings('ignore')\n",
                "\n",
                "from sqlalchemy import text\n",
                "from sklearn.metrics import mean_squared_error, mean_absolute_error\n",
                "import lightgbm as lgb\n",
                "\n",
                "project_root = Path.cwd().parent if Path.cwd().name == 'eda' else Path.cwd()\n",
                "sys.path.insert(0, str(project_root))\n",
                "\n",
                "from db.connection import get_db_engine\n",
                "\n",
                "plt.style.use('seaborn-v0_8-whitegrid' if 'seaborn-v0_8-whitegrid' in plt.style.available else 'default')\n",
                "plt.rcParams['figure.figsize'] = (14, 6)\n",
                "plt.rcParams['font.size'] = 11\n",
                "\n",
                "print(\"✅ Kütüphaneler ve veri bağlantı modülleri başarıyla yüklendi.\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 2. Silver Katmanı Verilerinin Birleştirilmesi (Baraj Su İmkânı Dahil Master Dataset)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "engine = get_db_engine()\n",
                "\n",
                "master_sql = text(\"\"\"\n",
                "    SELECT \n",
                "        m.ts,\n",
                "        m.price_usd AS mcp_price_usd,\n",
                "        m.price_try AS mcp_price_try,\n",
                "        s.system_marginal_price_try AS smp_price_try,\n",
                "        l.load_forecast_mw,\n",
                "        k.total_mw AS kgup_total_mw,\n",
                "        k.natural_gas_mw AS kgup_gas_mw,\n",
                "        k.wind_mw AS kgup_wind_mw,\n",
                "        k.solar_mw AS kgup_solar_mw,\n",
                "        k.dammed_hydro_mw + k.river_hydro_mw AS kgup_hydro_mw,\n",
                "        k.import_coal_mw + k.lignite_mw + k.black_coal_mw AS kgup_coal_mw,\n",
                "        g.total_mw AS actual_gen_total_mw,\n",
                "        c.consumption_mw AS actual_cons_mw,\n",
                "        w.turkey_weighted_temperature_c AS temperature_c,\n",
                "        mc.usd_try,\n",
                "        mc.brent_oil_usd,\n",
                "        ng.gas_reference_price_try AS natural_gas_grf_try,\n",
                "        wp.hydro_water_energy_mwh\n",
                "    FROM raw_mcp_hourly m\n",
                "    LEFT JOIN raw_smp_hourly s ON m.ts = s.ts\n",
                "    LEFT JOIN raw_load_forecast_hourly l ON m.ts = l.ts\n",
                "    LEFT JOIN raw_kgup_hourly k ON m.ts = k.ts\n",
                "    LEFT JOIN raw_actual_generation_hourly g ON m.ts = g.ts\n",
                "    LEFT JOIN raw_actual_consumption_hourly c ON m.ts = c.ts\n",
                "    LEFT JOIN raw_weather_hourly w ON m.ts = w.ts\n",
                "    LEFT JOIN raw_macro_daily mc ON DATE(m.ts) = mc.entry_date\n",
                "    LEFT JOIN raw_natural_gas_daily ng ON DATE(m.ts) = ng.entry_date\n",
                "    LEFT JOIN (\n",
                "        SELECT DATE(date_time) AS entry_date, SUM(water_energy_provision_mwh) AS hydro_water_energy_mwh\n",
                "        FROM raw_master_water_energy_provision\n",
                "        GROUP BY DATE(date_time)\n",
                "    ) wp ON DATE(m.ts) = wp.entry_date\n",
                "    ORDER BY m.ts ASC;\n",
                "\"\"\")\n",
                "\n",
                "with engine.connect() as conn:\n",
                "    df_raw = pd.read_sql(master_sql, conn)\n",
                "\n",
                "df_raw['ts'] = pd.to_datetime(df_raw['ts']).dt.tz_convert('Europe/Istanbul')\n",
                "df_raw = df_raw.set_index('ts').sort_index()\n",
                "\n",
                "df_raw['usd_try'] = df_raw['usd_try'].ffill().bfill()\n",
                "df_raw['brent_oil_usd'] = df_raw['brent_oil_usd'].ffill().bfill()\n",
                "df_raw['natural_gas_grf_try'] = df_raw['natural_gas_grf_try'].ffill().bfill()\n",
                "if 'hydro_water_energy_mwh' in df_raw.columns:\n",
                "    df_raw['hydro_water_energy_mwh'] = df_raw['hydro_water_energy_mwh'].ffill().bfill()\n",
                "\n",
                "print(f\"📊 Yüklenen Toplam Saatlik Satır Sayısı: {len(df_raw):,} saat ({df_raw.index.min()} ile {df_raw.index.max()} arası)\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 3. Gelecek Sızıntısız Öznitelik Mühendisliği (Data Leakage Free Pipeline)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "def build_features(df):\n",
                "    df_feat = df.copy()\n",
                "    \n",
                "    # A. Takvim Öznitelikleri\n",
                "    df_feat['hour'] = df_feat.index.hour\n",
                "    df_feat['dayofweek'] = df_feat.index.dayofweek\n",
                "    df_feat['month'] = df_feat.index.month\n",
                "    df_feat['quarter'] = df_feat.index.quarter\n",
                "    df_feat['is_weekend'] = (df_feat.index.dayofweek >= 5).astype(int)\n",
                "    df_feat['is_peak_hour'] = df_feat['hour'].isin([17, 18, 19, 20, 21]).astype(int)\n",
                "    \n",
                "    # B. Gecikmeli Fiyat Öznitelikleri (PTF en az 24 saat gecikme: T-1 biliniyor)\n",
                "    for lag in [24, 48, 168]:\n",
                "        df_feat[f'mcp_usd_lag_{lag}'] = df_feat['mcp_price_usd'].shift(lag)\n",
                "    \n",
                "    # C. Gecikmeli Plan ve Tahmin Öznitelikleri (En az 24 saat / 1 gün gecikmeli - T-1 planı)\n",
                "    for lag in [24, 48, 168]:\n",
                "        df_feat[f'load_lag_{lag}'] = df_feat['load_forecast_mw'].shift(lag)\n",
                "        df_feat[f'kgup_lag_{lag}'] = df_feat['kgup_total_mw'].shift(lag)\n",
                "        df_feat[f'kgup_wind_lag_{lag}'] = df_feat['kgup_wind_mw'].shift(lag)\n",
                "        df_feat[f'kgup_solar_lag_{lag}'] = df_feat['kgup_solar_mw'].shift(lag)\n",
                "        df_feat[f'kgup_hydro_lag_{lag}'] = df_feat['kgup_hydro_mw'].shift(lag)\n",
                "        df_feat[f'kgup_gas_lag_{lag}'] = df_feat['kgup_gas_mw'].shift(lag)\n",
                "    \n",
                "    # D. Gecikmeli Gerçekleşen Veriler (Gerçekleşen Tüketim/Üretim en az 48 saat gecikme: T-2 biliniyor)\n",
                "    for lag in [48, 168]:\n",
                "        if 'actual_gen_total_mw' in df_feat.columns:\n",
                "            df_feat[f'actual_gen_lag_{lag}'] = df_feat['actual_gen_total_mw'].shift(lag)\n",
                "        if 'actual_cons_mw' in df_feat.columns:\n",
                "            df_feat[f'actual_cons_lag_{lag}'] = df_feat['actual_cons_mw'].shift(lag)\n",
                "    \n",
                "    # E. Hareketli İstatistikler\n",
                "    df_feat['mcp_usd_roll_mean_24h'] = df_feat['mcp_price_usd'].shift(24).rolling(window=24).mean()\n",
                "    df_feat['mcp_usd_roll_std_24h'] = df_feat['mcp_price_usd'].shift(24).rolling(window=24).std()\n",
                "    df_feat['mcp_usd_roll_mean_7d'] = df_feat['mcp_price_usd'].shift(24).rolling(window=168).mean()\n",
                "    \n",
                "    # F. Arz-Talep Dengesi & Yenilenebilir Oranlar (1 Gün Önceki Plan/KGÜP Verisiyle - shift(24))\n",
                "    df_feat['supply_demand_gap_mw'] = df_feat['load_lag_24'] - df_feat['kgup_lag_24']\n",
                "    total_kgup_safe = df_feat['kgup_lag_24'].replace(0, np.nan)\n",
                "    df_feat['renewable_ratio'] = (df_feat['kgup_wind_lag_24'] + df_feat['kgup_solar_lag_24'] + df_feat['kgup_hydro_lag_24']) / total_kgup_safe\n",
                "    df_feat['renewable_ratio'] = df_feat['renewable_ratio'].fillna(0)\n",
                "    \n",
                "    # G. Güneş & Rüzgar Zirve Oranı\n",
                "    df_feat['solar_wind_ratio'] = (df_feat['kgup_wind_lag_24'] + df_feat['kgup_solar_lag_24']) / total_kgup_safe\n",
                "    df_feat['solar_wind_ratio'] = df_feat['solar_wind_ratio'].fillna(0)\n",
                "    \n",
                "    return df_feat\n",
                "\n",
                "df_feat = build_features(df_raw)\n",
                "df_model = df_feat.dropna().copy()\n",
                "\n",
                "target_col = 'mcp_price_usd'\n",
                "exclude_cols = [\n",
                "    'mcp_price_usd', 'mcp_price_try', 'smp_price_try', \n",
                "    'actual_gen_total_mw', 'actual_cons_mw',\n",
                "    'load_forecast_mw', 'kgup_total_mw', 'kgup_gas_mw', \n",
                "    'kgup_wind_mw', 'kgup_solar_mw', 'kgup_hydro_mw', 'kgup_coal_mw'\n",
                "]\n",
                "feature_cols = [c for c in df_model.columns if c not in exclude_cols]\n",
                "\n",
                "# Metrik Hesaplama Fonksiyonları\n",
                "def calculate_safe_mape(y_true, y_pred):\n",
                "    safe_denom = np.maximum(y_true, 1.0)\n",
                "    return np.mean(np.abs((y_true - y_pred) / safe_denom)) * 100\n",
                "\n",
                "def calculate_wape(y_true, y_pred):\n",
                "    sum_actual = np.sum(np.abs(y_true))\n",
                "    if sum_actual == 0:\n",
                "        return 0.0\n",
                "    return (np.sum(np.abs(y_true - y_pred)) / sum_actual) * 100\n",
                "\n",
                "print(f\"✨ Temizlenmiş Model Dataseti Hazır: {len(df_model):,} saat | Değişken Sayısı: {len(feature_cols)}\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 4. Genel Günlük Walk-Forward Backtest Motoru (MAE, MAPE & WAPE Metrikleriyle)\n",
                "Tüm model denemelerinde standart olarak kullanılacak **3, 6, 9 ve 12 Aylık (365 Gün) Günlük Backtest** motoru."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "def run_daily_walk_forward_backtest(df_data, feature_list, target_name, train_predict_fn, max_days=365, lookback_hours=4380):\n",
                "    daily_results = []\n",
                "    \n",
                "    for day_idx in range(max_days):\n",
                "        test_end = df_data.index.max() - pd.Timedelta(days=day_idx)\n",
                "        test_start = test_end - pd.Timedelta(hours=23)\n",
                "        train_end = test_start - pd.Timedelta(hours=1)\n",
                "        train_start = train_end - pd.Timedelta(hours=lookback_hours)\n",
                "        \n",
                "        tr_df = df_data.loc[train_start:train_end]\n",
                "        te_df = df_data.loc[test_start:test_end]\n",
                "        \n",
                "        if len(tr_df) < 1000 or len(te_df) < 12:\n",
                "            continue\n",
                "            \n",
                "        preds = train_predict_fn(tr_df, te_df, feature_list, target_name)\n",
                "        \n",
                "        y_true = te_df[target_name].values\n",
                "        mae = mean_absolute_error(y_true, preds)\n",
                "        mape = calculate_safe_mape(y_true, preds)\n",
                "        wape = calculate_wape(y_true, preds)\n",
                "        \n",
                "        daily_results.append({\n",
                "            'day_offset': day_idx,\n",
                "            'tarih': test_start.strftime('%Y-%m-%d'),\n",
                "            'mae': mae,\n",
                "            'mape': mape,\n",
                "            'wape': wape\n",
                "        })\n",
                "        \n",
                "        if (day_idx + 1) % 5 == 0 or (day_idx + 1) == max_days or max_days <= 10:\n",
                "            pct = ((day_idx + 1) / max_days) * 100\n",
                "            print(f\"⏳ [{day_idx+1:02d}/{max_days:02d}] ({pct:5.1f}%) | Tarih: {test_start.strftime('%Y-%m-%d')} | MAE: ${mae:5.2f}/MWh | WAPE: %{wape:5.2f}\")\n",
                "        \n",
                "    res_df = pd.DataFrame(daily_results)\n",
                "    \n",
                "    horizon_summary = []\n",
                "    for m_num, d_cnt in [(3, 90), (6, 180), (9, 270), (12, 365)]:\n",
                "        sub = res_df.iloc[:min(d_cnt, len(res_df))]\n",
                "        horizon_summary.append({\n",
                "            'Test Dönemi': f'Son {m_num} Ay ({len(sub)} Gün)',\n",
                "            'Ortalama MAE ($/MWh)': round(sub['mae'].mean(), 2),\n",
                "            'Ortalama MAPE (%)': round(sub['mape'].mean(), 2),\n",
                "            'Ortalama WAPE (%)': round(sub['wape'].mean(), 2)\n",
                "        })\n",
                "        \n",
                "    return pd.DataFrame(horizon_summary), res_df\n",
                "\n",
                "print(\"⚙️ WAPE Destekli Günlük Walk-Forward Backtest Motoru Yüklendi.\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 🧪 DENEME 1: LightGBM Baseline Model (Günlük Re-training & 24 Saat Tahmin)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "def train_predict_lgb_baseline(train_df, test_df, features, target):\n",
                "    model = lgb.LGBMRegressor(n_estimators=200, learning_rate=0.03, verbose=-1, random_state=42)\n",
                "    model.fit(train_df[features], train_df[target])\n",
                "    return model.predict(test_df[features])\n",
                "\n",
                "print(\"🚀 DENEME 1: LightGBM Baseline 365-Günlük Backtest Başlatılıyor...\")\n",
                "lgb_summary, lgb_daily = run_daily_walk_forward_backtest(df_model, feature_cols, target_col, train_predict_lgb_baseline, max_days=365)\n",
                "\n",
                "print(\"=\" * 95)\n",
                "print(\"📊 DENEME 1: LIGHTGBM BASELINE 3, 6, 9 VE 12 AYLIK GÜNLÜK BACKTEST SONUÇLARI (MAE, MAPE, WAPE)\")\n",
                "print(\"=\" * 95)\n",
                "print(lgb_summary.to_string(index=False))\n",
                "print(\"=\" * 95)"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 🧪 DENEME 2 (NİHAİ BAŞARILI): 2026 Rejim Değişimi Uyarlamalı İyileştirilmiş Model\n",
                "*(1. Hedef Değişken Log-Transform (`log1p(price)` & `expm1`), 2. Baraj Su Enerjisi İmkânı (`hydro_water_energy_mwh`), 3. Güneş/Rüzgar Zirve Oranları Öznitelikleri)*"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "def train_predict_lgb_log_hydro(train_df, test_df, features, target):\n",
                "    # Logaritmik hedef değişken eğitimi (Log1p)\n",
                "    y_tr_log = np.log1p(train_df[target])\n",
                "    model = lgb.LGBMRegressor(n_estimators=300, learning_rate=0.03, verbose=-1, random_state=42)\n",
                "    model.fit(train_df[features], y_tr_log)\n",
                "    \n",
                "    # Tahminlerin geri dönüştürülmesi (Expm1 & Non-negative Clip)\n",
                "    preds_log = model.predict(test_df[features])\n",
                "    preds = np.expm1(preds_log)\n",
                "    return np.maximum(preds, 0.0)\n",
                "\n",
                "print(\"🚀 DENEME 2: İyileştirilmiş Model (Log Transform + Baraj Su İmkânı) 365-Günlük Backtest Başlatılıyor...\")\n",
                "exp2_summary, exp2_daily = run_daily_walk_forward_backtest(df_model, feature_cols, target_col, train_predict_lgb_log_hydro, max_days=365)\n",
                "\n",
                "print(\"=\" * 95)\n",
                "print(\"🏆 DENEME 2: İYİLEŞTİRİLMİŞ MODEL 3, 6, 9 VE 12 AYLIK GÜNLÜK BACKTEST SONUÇLARI (MAE, MAPE, WAPE)\")\n",
                "print(\"=\" * 95)\n",
                "print(exp2_summary.to_string(index=False))\n",
                "print(\"=\" * 95)"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 🧪 DENEME 3: EPNet Derin Öğrenme Mimarisi (CNN-LSTM Hybrid PyTorch Model)\n",
                "*(Makale: 'An Electricity Price Forecasting Model by Hybrid Structured Deep Neural Networks', Kuo & Huang 2018 - 1D-CNN Feature Extractor + LSTM Forecasting)*"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import torch\n",
                "import torch.nn as nn\n",
                "import torch.optim as optim\n",
                "from torch.utils.data import TensorDataset, DataLoader\n",
                "from sklearn.preprocessing import StandardScaler\n",
                "\n",
                "class EPNet(nn.Module):\n",
                "    def __init__(self, input_dim, cnn_out_channels=32, lstm_hidden_dim=32):\n",
                "        super(EPNet, self).__init__()\n",
                "        # 1D-CNN Feature Extraction\n",
                "        self.conv1 = nn.Conv1d(in_channels=input_dim, out_channels=cnn_out_channels, kernel_size=3, padding=1)\n",
                "        self.relu1 = nn.ReLU()\n",
                "        self.pool1 = nn.MaxPool1d(kernel_size=2, stride=2, padding=1)\n",
                "        \n",
                "        self.conv2 = nn.Conv1d(in_channels=cnn_out_channels, out_channels=cnn_out_channels, kernel_size=3, padding=1)\n",
                "        self.bn2 = nn.BatchNorm1d(num_features=cnn_out_channels)\n",
                "        self.relu2 = nn.ReLU()\n",
                "        self.pool2 = nn.MaxPool1d(kernel_size=2, stride=2, padding=1)\n",
                "        \n",
                "        # LSTM Forecasting\n",
                "        self.lstm = nn.LSTM(input_size=cnn_out_channels, hidden_size=lstm_hidden_dim, batch_first=True)\n",
                "        self.relu3 = nn.ReLU()\n",
                "        self.fc = nn.Linear(lstm_hidden_dim, 1)\n",
                "        \n",
                "    def forward(self, x):\n",
                "        x = x.permute(0, 2, 1)\n",
                "        x = self.pool1(self.relu1(self.conv1(x)))\n",
                "        x = self.pool2(self.relu2(self.bn2(self.conv2(x))))\n",
                "        x = x.permute(0, 2, 1)\n",
                "        lstm_out, _ = self.lstm(x)\n",
                "        out = self.relu3(lstm_out[:, -1, :])\n",
                "        out = self.fc(out)\n",
                "        return out.squeeze(-1)\n",
                "\n",
                "def train_predict_epnet_paper(train_df, test_df, features, target, seq_len=24, epochs=10):\n",
                "    scaler = StandardScaler()\n",
                "    X_tr_s = scaler.fit_transform(train_df[features].values)\n",
                "    y_tr_log = np.log1p(np.maximum(train_df[target].values, 0.0))\n",
                "    \n",
                "    X_te_s = scaler.transform(test_df[features].values)\n",
                "    \n",
                "    # Create sequences\n",
                "    X_tr_seq, y_tr_seq = [], []\n",
                "    for i in range(len(X_tr_s) - seq_len + 1):\n",
                "        X_tr_seq.append(X_tr_s[i:i+seq_len])\n",
                "        y_tr_seq.append(y_tr_log[i+seq_len-1])\n",
                "        \n",
                "    X_tr_t = torch.tensor(np.array(X_tr_seq), dtype=torch.float32)\n",
                "    y_tr_t = torch.tensor(np.array(y_tr_seq), dtype=torch.float32)\n",
                "    \n",
                "    # Test sequence (pad with last train sequence)\n",
                "    X_full_s = np.vstack([X_tr_s[-(seq_len-1):], X_te_s])\n",
                "    X_te_seq = []\n",
                "    for i in range(len(X_te_s)):\n",
                "        X_te_seq.append(X_full_s[i:i+seq_len])\n",
                "    X_te_t = torch.tensor(np.array(X_te_seq), dtype=torch.float32)\n",
                "    \n",
                "    dataset = TensorDataset(X_tr_t, y_tr_t)\n",
                "    loader = DataLoader(dataset, batch_size=128, shuffle=True)\n",
                "    \n",
                "    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
                "    model = EPNet(input_dim=len(features)).to(device)\n",
                "    optimizer = optim.Adam(model.parameters(), lr=0.003)\n",
                "    criterion = nn.MSELoss()\n",
                "    \n",
                "    model.train()\n",
                "    for epoch in range(epochs):\n",
                "        for bx, by in loader:\n",
                "            bx, by = bx.to(device), by.to(device)\n",
                "            optimizer.zero_grad()\n",
                "            loss = criterion(model(bx), by)\n",
                "            loss.backward()\n",
                "            optimizer.step()\n",
                "            \n",
                "    model.eval()\n",
                "    with torch.no_grad():\n",
                "        preds_log = model(X_te_t.to(device)).cpu().numpy()\n",
                "        \n",
                "    preds = np.expm1(preds_log)\n",
                "    return np.maximum(preds, 0.0)\n",
                "\n",
                "print(\"🚀 DENEME 3: EPNet (CNN-LSTM Hybrid PyTorch) 7-Günlük Hızlı Notebook Backtest Başlatılıyor...\")\n",
                "# Notebook ortamında hızlı çalışması için varsayılan max_days=7 olarak ayarlanmıştır.\n",
                "# Uzun dönemli (30, 90, 365 gün) backtest için terminalden 'python run_epnet_backtest.py --days 90' çalıştırabilirsiniz.\n",
                "epnet_summary, epnet_daily = run_daily_walk_forward_backtest(df_model, feature_cols, target_col, train_predict_epnet_paper, max_days=7)\n",
                "\n",
                "print(\"=\" * 95)\n",
                "print(\"🧠 DENEME 3: EPNET (CNN-LSTM DERİN ÖĞRENME) 7-GÜNLÜK BACKTEST SONUÇLARI (MAE, MAPE, WAPE)\")\n",
                "print(\"=\" * 95)\n",
                "print(epnet_summary.to_string(index=False))\n",
                "print(\"=\" * 95)"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 📊 5. Model Denemeleri Karşılaştırma Rehberi\n",
                "\n",
                "> ℹ️ **Not:** Yukarıdaki kod hücreleri çalıştırıldığında kendi canlı veritabanınız üzerindeki kesin MAE, MAPE ve WAPE sonuçları dinamik olarak basılır.\n",
                ">\n",
                "> 💡 **Derin Öğrenme Notu:** PyTorch tabanlı **EPNet (CNN-LSTM)** modelini 365 günlük uzun walk-forward döngüsünde çalıştırmak için terminalden aşağıdaki komutu kullanabilirsiniz:\n",
                "> ```bash\n",
                "> python run_epnet_backtest.py --days 30\n",
                "> ```"
            ]
        }
    ],
    "metadata": {
        "language_info": {
            "name": "python"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 2
}

output_path = Path("eda/02_model_experiments_daily_forecasting.ipynb")
output_path.parent.mkdir(parents=True, exist_ok=True)
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=2, ensure_ascii=False)

print(f"✅ Dedicated notebook eda/02_model_experiments_daily_forecasting.ipynb updated with WAPE at: {output_path.resolve()}")
